export const dashboard = {
  notifications: "Avisos",
  viewAll: "Ver tudo",
  clear: "Limpar",
  emptyNotifications: "Tudo quieto por aqui.",
  account: "Conta",
  preferences: "Preferências",
  organization: "Organização",
  profileCard: "Seu card no NaBola",
  playerData: "Dados do jogador",
  cardUsage: "Uso do card",
  cardUsageTitle: "Ranking, perfil e comparações.",
  cardUsageDescription: "O card vira a identidade do jogador dentro da pelada, sem copiar visual de game famoso.", dashboard: "Seu painel", dashboardDescription: "Agenda, avisos e desempenho em um lugar só.", refresh: "Atualizar", createFirstTeam: "Comece pelo primeiro time", createFirstTeamDescription: "O dashboard ganha agenda, ranking e ações assim que você entra em um elenco.", actionQueue: "Fila de jogo", actionQueueTitle: "O que pede sua atenção",
  settingsTitle: "Ajustes",
  settingsDescription: "Esta rota separa configurações de conta do card de jogador, deixando o perfil livre para identidade, números e histórico.", alerts: "Avisos", recentNotes: "Recados recentes", readAll: "Ler tudo", allGood: "Tudo certo por aqui.", alertsDescription: "Convites, alterações de partida e campeonatos aparecem neste espaço.", matchCenter: "Central da rodada", matchCenterTitle: "Leitura rápida do que importa", scheduled: "A jogar", scheduledHelper: "Partidas no radar", completed: "Fechados", completedHelper: "Placares resolvidos", pendingInvites: "Convites", pendingInvitesHelper: "Pendências da turma", highlightedTeam: "Time em destaque", createTeamPrompt: "Crie um time para abrir a disputa", rankingSummary: "Ranking, forma e campanha aparecem aqui.", form: "Forma", completeMatch: "Concluir partida", rankingDescription: "O ranking de jogadores aparece depois das primeiras súmulas fechadas.", rankingWarming: "Ranking em aquecimento", playerRanking: "Ranking de jogadores", crewHighlights: "Destaques da turma", viewRanking: "Ver ranking"
  , notificationsTitle: "Notificações", notificationsDescription: "Mudanças importantes da sua turma aparecem aqui.", notificationsEmpty: "Tudo quieto por aqui.", notificationsLoading: "Abrindo avisos...", notificationsMarkedRead: "Avisos marcados como lidos.", notificationsMarkReadError: "Não foi possível marcar os avisos como lidos.", notificationMarkReadError: "Não foi possível atualizar o aviso.", new: "Novo", notificationInviteCreatedTitle: "Novo convite", notificationInviteCreatedMessage: "Você recebeu um convite para {teamName}.", notificationInviteCreatedFallbackMessage: "Você recebeu um novo convite de time.", notificationInviteAcceptedTitle: "Convite aceito", notificationInviteAcceptedMessage: "{username} entrou em {teamName}.", notificationInviteAcceptedFallbackMessage: "Um convite de time foi aceito.", notificationMatchScheduledTitle: "Partida marcada", notificationMatchScheduledMessage: "{homeTeam} x {awayTeam} foi marcada.", notificationMatchScheduledFallbackMessage: "Uma nova partida foi marcada.", notificationMatchCompletedTitle: "Partida encerrada", notificationMatchCompletedMessage: "{homeTeam} {homeScore} x {awayScore} {awayTeam}.", notificationMatchCompletedFallbackMessage: "Uma partida foi encerrada.", notificationMatchCancelledTitle: "Partida cancelada", notificationMatchCancelledMessage: "Uma partida foi cancelada no NaBola.", notificationPresenceUpdatedTitle: "Presença atualizada", notificationPresenceUpdatedMessage: "A presença em uma partida foi atualizada.", notificationTeamMemberAddedTitle: "Você entrou em um time", notificationTeamMemberAddedMessage: "Agora você faz parte de {teamName}.", notificationTeamMemberAddedFallbackMessage: "Você entrou em um time.", notificationTournamentUpdatedTitle: "Tabela atualizada", notificationTournamentUpdatedMessage: "A tabela de {tournamentName} foi atualizada.", notificationTournamentUpdatedFallbackMessage: "A tabela de um campeonato foi atualizada.", matchScheduled: "Jogo marcado", invitePending: "Convite pendente"
} as const;
