export const dashboard = {
  notifications: "Notifications",
  viewAll: "View all",
  clear: "Clear",
  emptyNotifications: "All quiet here.",
  account: "Account",
  preferences: "Preferences",
  organization: "Organization",
  profileCard: "Your NaBola card",
  playerData: "Player details",
  cardUsage: "Card usage",
  cardUsageTitle: "Ranking, profile and comparisons.",
  cardUsageDescription: "The card becomes the player's identity in the crew, without copying a famous game interface.", dashboard: "Your dashboard", dashboardDescription: "Schedule, alerts and performance in one place.", refresh: "Refresh", createFirstTeam: "Start with your first team", createFirstTeamDescription: "The dashboard gets a schedule, ranking and actions as soon as you join a squad.", actionQueue: "Match queue", actionQueueTitle: "What needs your attention",
  settingsTitle: "Settings",
  settingsDescription: "This route separates account settings from the player card, keeping the profile focused on identity, numbers and history.", alerts: "Alerts", recentNotes: "Recent notes", readAll: "Read all", allGood: "All good here.", alertsDescription: "Invites, match changes and cups appear in this space.", matchCenter: "Round center", matchCenterTitle: "A quick read on what matters", scheduled: "Upcoming", scheduledHelper: "Matches on the radar", completed: "Closed", completedHelper: "Resolved scores", pendingInvites: "Invites", pendingInvitesHelper: "Crew tasks", highlightedTeam: "Team in focus", createTeamPrompt: "Create a team to start the competition", rankingSummary: "Ranking, form and campaign appear here.", form: "Form", completeMatch: "Complete match", rankingDescription: "The player ranking appears after the first match sheets are closed.", rankingWarming: "Ranking warming up", playerRanking: "Player ranking", crewHighlights: "Crew highlights", viewRanking: "View ranking"
  , notificationsTitle: "Notifications", notificationsDescription: "Important changes from your crew appear here.", notificationsEmpty: "All quiet here.", notificationsLoading: "Opening notifications...", notificationsMarkedRead: "Alerts marked as read.", notificationsMarkReadError: "Could not mark the alerts as read.", notificationMarkReadError: "Could not update the notification.", new: "New", notificationInviteCreatedTitle: "New invite", notificationInviteCreatedMessage: "You received an invite to {teamName}.", notificationInviteCreatedFallbackMessage: "You received a new team invite.", notificationInviteAcceptedTitle: "Invite accepted", notificationInviteAcceptedMessage: "{username} joined {teamName}.", notificationInviteAcceptedFallbackMessage: "A team invite was accepted.", notificationMatchScheduledTitle: "Match scheduled", notificationMatchScheduledMessage: "{homeTeam} vs {awayTeam} was scheduled.", notificationMatchScheduledFallbackMessage: "A new match was scheduled.", notificationMatchCompletedTitle: "Match completed", notificationMatchCompletedMessage: "{homeTeam} {homeScore} vs {awayScore} {awayTeam}.", notificationMatchCompletedFallbackMessage: "A match was completed.", notificationMatchCancelledTitle: "Match cancelled", notificationMatchCancelledMessage: "A match was cancelled on NaBola.", notificationPresenceUpdatedTitle: "Presence updated", notificationPresenceUpdatedMessage: "A match presence was updated.", notificationTeamMemberAddedTitle: "You joined a team", notificationTeamMemberAddedMessage: "You are now part of {teamName}.", notificationTeamMemberAddedFallbackMessage: "You joined a team.", notificationTournamentUpdatedTitle: "Standings updated", notificationTournamentUpdatedMessage: "The {tournamentName} standings were updated.", notificationTournamentUpdatedFallbackMessage: "Tournament standings were updated.", matchScheduled: "Match scheduled", invitePending: "Pending invite"
} as const;
